### ISSUE TITLE
How do I build/install?

### ISSUE THREAD

**Issue by ThePhantomGamer** [GreenTurtwig/Material-Colours#1]
Hey I wanted to try this out on my Linux machine and I didn't see any building instructions...

**Comment by GreenTurtwig** [comment]
Sorry about the late reply... 😿
You should be able to simply visit the [releases](https://github.com/GreenTurtwig/Material-Colours/releases) page and download the Linux archive. When extracted you can run the `Material-Colours` file to open it up. 👍  
Do bear in mind that I'm no longer working on this though, since it was sooo long ago. :-(

**Comment by ThePhantomGamer** [comment]
Ok, thanks :smile:
